name: ModernShowcase
main: me.dru.showcase.ModernShowcase
version: 1.1
description: "A good showcase plugin"
author: Dru_TNT
softdepend: [CoreProtect]
api-version: 1.19
commands:
  ModernShowcase:
    description: "ModernShowcase management command"
    aliases: [ms,showcase]